name: cold_river_express_app
description: "Help people during their move to catalog boxes and print labels"

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  shared_preferences: ^2.5.2
  flutter_esc_pos_utils: ^1.0.1
  print_bluetooth_thermal: ^1.1.6
  provider: ^6.1.2
  speech_to_text: ^7.0.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  share_plus: ^10.1.4
  permission_handler: ^11.4.0
  flutter_colorpicker: ^1.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^9.1.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon-appbar.png

flutter_launcher_icons:
  image_path_android: "assets/icons/icon-710x599-android.png"
  image_path_ios: "assets/icons/icon-1024x1024.png"
  ios: true 
  android: true 
  adaptive_icon_foreground: "assets/icons/icon-foreground-432x432.png" 
  adaptive_icon_foreground_inset: 16 
  adaptive_icon_monochrome: "assets/icons/icon-monochrome-432x432.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_background: "#ffffff"